// <auto-generated />
namespace HaarlemFestival.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig25));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181340565_mig25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
